/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class Eszak2 extends javax.swing.JFrame {

    /**
     * Creates new form Eszak2
     */
    public Eszak2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSzoveg4 = new javax.swing.JLabel();
        lblSzoveg = new javax.swing.JLabel();
        lblSzoveg2 = new javax.swing.JLabel();
        lblSzoveg3 = new javax.swing.JLabel();
        btnHarc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSzoveg4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg4.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg4.setText("Előhúzod a kardod, és felkészülsz a harcra!");
        getContentPane().add(lblSzoveg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        lblSzoveg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg.setText("Hallod, hogy elölről súlyos lépések közelednek.");
        getContentPane().add(lblSzoveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        lblSzoveg2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg2.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg2.setText("Egy széles, állatbőrökbe öltözött, kőbaltás, primitívlény lép elő. ");
        getContentPane().add(lblSzoveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblSzoveg3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg3.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg3.setText("Ahogy meglát, morog, a földre köp, majd a kőbaltával közeledik");
        getContentPane().add(lblSzoveg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnHarc.setBackground(new java.awt.Color(255, 51, 51));
        btnHarc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHarc.setForeground(new java.awt.Color(255, 255, 255));
        btnHarc.setText("HARC!");
        btnHarc.setMinimumSize(new java.awt.Dimension(80, 30));
        btnHarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarcActionPerformed(evt);
            }
        });
        getContentPane().add(btnHarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hattereszak.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarcActionPerformed
        dispose();
    }//GEN-LAST:event_btnHarcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eszak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eszak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eszak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eszak2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eszak2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHarc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSzoveg;
    private javax.swing.JLabel lblSzoveg2;
    private javax.swing.JLabel lblSzoveg3;
    private javax.swing.JLabel lblSzoveg4;
    // End of variables declaration//GEN-END:variables
}
