/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class JatekForm extends javax.swing.JFrame {

    /**
     * Creates new form JatekForm
     */
    public JatekForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSzoveg = new javax.swing.JLabel();
        lblSzoveg2 = new javax.swing.JLabel();
        lblSzoveg3 = new javax.swing.JLabel();
        lblSzoveg4 = new javax.swing.JLabel();
        lblSzoveg5 = new javax.swing.JLabel();
        btnEszak = new javax.swing.JButton();
        btnDoboz = new javax.swing.JButton();
        lblHatter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSzoveg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg.setText("Miután öt percet haladtál lassan az alagútban, egy kőasztalhoz érsz, ");
        getContentPane().add(lblSzoveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblSzoveg2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg2.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg2.setText("amely a bal oldali fal mellett áll. ");
        getContentPane().add(lblSzoveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        lblSzoveg3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg3.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg3.setText("Hat doboz van rajta, egyikükre a te neved festették. ");
        getContentPane().add(lblSzoveg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        lblSzoveg4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg4.setForeground(new java.awt.Color(255, 255, 0));
        lblSzoveg4.setText("Választhatsz, kinyitod a dobozt,");
        getContentPane().add(lblSzoveg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        lblSzoveg5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg5.setForeground(new java.awt.Color(255, 255, 0));
        lblSzoveg5.setText("vagy haladsz tovább észak felé");
        getContentPane().add(lblSzoveg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        btnEszak.setBackground(new java.awt.Color(255, 51, 51));
        btnEszak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEszak.setForeground(new java.awt.Color(255, 255, 255));
        btnEszak.setText("MEGYEK ÉSZAK FELÉ");
        btnEszak.setMinimumSize(new java.awt.Dimension(80, 30));
        btnEszak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEszakActionPerformed(evt);
            }
        });
        getContentPane().add(btnEszak, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 300, 100));

        btnDoboz.setBackground(new java.awt.Color(255, 51, 51));
        btnDoboz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDoboz.setForeground(new java.awt.Color(255, 255, 255));
        btnDoboz.setText("KINYITOM A DOBOZT");
        btnDoboz.setMinimumSize(new java.awt.Dimension(80, 30));
        btnDoboz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDobozActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoboz, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 300, 100));

        lblHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hatter.jpg"))); // NOI18N
        lblHatter.setText("jLabel1");
        getContentPane().add(lblHatter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDobozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDobozActionPerformed
       new KinyitodDoboz().setVisible(true);
       dispose();
    }//GEN-LAST:event_btnDobozActionPerformed

    private void btnEszakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEszakActionPerformed
     new Eszak().setVisible(true);
     dispose();
    }//GEN-LAST:event_btnEszakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JatekForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JatekForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JatekForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JatekForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JatekForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoboz;
    private javax.swing.JButton btnEszak;
    private javax.swing.JLabel lblHatter;
    private javax.swing.JLabel lblSzoveg;
    private javax.swing.JLabel lblSzoveg2;
    private javax.swing.JLabel lblSzoveg3;
    private javax.swing.JLabel lblSzoveg4;
    private javax.swing.JLabel lblSzoveg5;
    // End of variables declaration//GEN-END:variables
}
