/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class Karakterek extends javax.swing.JFrame {

    /**
     * Creates new form Karakterek
     */
    public Karakterek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlKarakter = new javax.swing.JPanel();
        rdbHarcos = new javax.swing.JRadioButton();
        rdbVarazslo = new javax.swing.JRadioButton();
        lblKep = new javax.swing.JLabel();
        btnKivalaszt = new javax.swing.JButton();
        btnMegsem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblManaszoveg = new javax.swing.JLabel();
        lblEletszoveg = new javax.swing.JLabel();
        lblSebzes = new javax.swing.JLabel();
        lblElet = new javax.swing.JLabel();
        lblSebzesszoveg = new javax.swing.JLabel();
        lblMana = new javax.swing.JLabel();
        lblHarcos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlKarakter.setBorder(javax.swing.BorderFactory.createTitledBorder("Válassz karaktert:"));

        buttonGroup1.add(rdbHarcos);
        rdbHarcos.setSelected(true);
        rdbHarcos.setText("Harcos");

        buttonGroup1.add(rdbVarazslo);
        rdbVarazslo.setText("Varázsló");
        rdbVarazslo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbVarazsloItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlKarakterLayout = new javax.swing.GroupLayout(pnlKarakter);
        pnlKarakter.setLayout(pnlKarakterLayout);
        pnlKarakterLayout.setHorizontalGroup(
            pnlKarakterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKarakterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlKarakterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbVarazslo)
                    .addComponent(rdbHarcos))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlKarakterLayout.setVerticalGroup(
            pnlKarakterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKarakterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbHarcos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbVarazslo)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/varazslo.jpg"))); // NOI18N
        lblKep.setMaximumSize(new java.awt.Dimension(961, 740));
        lblKep.setMinimumSize(new java.awt.Dimension(961, 740));

        btnKivalaszt.setText("Kiválaszt");
        btnKivalaszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKivalasztActionPerformed(evt);
            }
        });

        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Statisztikák:"));

        lblManaszoveg.setText("Mana:");

        lblEletszoveg.setText("Életerő:");

        lblSebzes.setText("80");

        lblElet.setText("120");

        lblSebzesszoveg.setText("Sebzés:");

        lblMana.setText("60");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSebzesszoveg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSebzes))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEletszoveg)
                            .addComponent(lblManaszoveg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElet)
                            .addComponent(lblMana))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblElet, lblMana, lblSebzes});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEletszoveg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblManaszoveg))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblElet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMana)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSebzesszoveg)
                    .addComponent(lblSebzes))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblElet, lblMana, lblSebzes});

        lblHarcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/harcossss.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnlKarakter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKivalaszt)
                    .addComponent(btnMegsem))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHarcos)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlKarakter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKivalaszt)
                .addGap(27, 27, 27)
                .addComponent(btnMegsem)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHarcos)
                .addGap(18, 18, 18)
                .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKivalasztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKivalasztActionPerformed
        dispose();
    }//GEN-LAST:event_btnKivalasztActionPerformed

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        dispose();
    }//GEN-LAST:event_btnMegsemActionPerformed

    private void rdbVarazsloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbVarazsloItemStateChanged
        if(rdbVarazslo.isSelected()){
        lblElet.setText("80");
        lblMana.setText("120");
        lblSebzes.setText("100");
        } else{
        lblElet.setText("120");
        lblMana.setText("60");
        lblSebzes.setText("80");
        }
         
    }//GEN-LAST:event_rdbVarazsloItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karakterek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karakterek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karakterek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karakterek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karakterek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKivalaszt;
    private javax.swing.JButton btnMegsem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblElet;
    private javax.swing.JLabel lblEletszoveg;
    private javax.swing.JLabel lblHarcos;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblMana;
    private javax.swing.JLabel lblManaszoveg;
    private javax.swing.JLabel lblSebzes;
    private javax.swing.JLabel lblSebzesszoveg;
    private javax.swing.JPanel pnlKarakter;
    private javax.swing.JRadioButton rdbHarcos;
    private javax.swing.JRadioButton rdbVarazslo;
    // End of variables declaration//GEN-END:variables
}
