/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class Kelet extends javax.swing.JFrame {

    /**
     * Creates new form Kelet
     */
    public Kelet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSzoveg3 = new javax.swing.JLabel();
        lblSzoveg = new javax.swing.JLabel();
        lblSzoveg2 = new javax.swing.JLabel();
        btnKettevag = new javax.swing.JButton();
        btnAtmasz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSzoveg3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg3.setForeground(new java.awt.Color(255, 255, 0));
        lblSzoveg3.setText("Választhatsz, hogy átmászol rajta, vagy kettévágod a kardoddal!");
        getContentPane().add(lblSzoveg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblSzoveg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg.setText("Látod, hogy az akadály egy széles, barna, sziklaszerű tárgy.");
        getContentPane().add(lblSzoveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        lblSzoveg2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg2.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg2.setText("Megérinted, és meglepve tapasztalod, hogy lágy, szivacsszerű.");
        getContentPane().add(lblSzoveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        btnKettevag.setBackground(new java.awt.Color(255, 51, 51));
        btnKettevag.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        btnKettevag.setForeground(new java.awt.Color(255, 255, 255));
        btnKettevag.setText("KETTÉVÁG");
        btnKettevag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKettevagActionPerformed(evt);
            }
        });
        getContentPane().add(btnKettevag, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 150, 90));

        btnAtmasz.setBackground(new java.awt.Color(255, 51, 51));
        btnAtmasz.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        btnAtmasz.setForeground(new java.awt.Color(255, 255, 255));
        btnAtmasz.setText("ÁTMÁSZOL");
        btnAtmasz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtmaszActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtmasz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 150, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hattereszak.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKettevagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKettevagActionPerformed
       new Kettevag().setVisible(true);
       dispose();
    }//GEN-LAST:event_btnKettevagActionPerformed

    private void btnAtmaszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtmaszActionPerformed
       new Atmaszol().setVisible(true);
       dispose();
    }//GEN-LAST:event_btnAtmaszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kelet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtmasz;
    private javax.swing.JButton btnKettevag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSzoveg;
    private javax.swing.JLabel lblSzoveg2;
    private javax.swing.JLabel lblSzoveg3;
    // End of variables declaration//GEN-END:variables
}
