/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class Kettevag extends javax.swing.JFrame {

    /**
     * Creates new form Kettevag
     */
    public Kettevag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSzoveg2 = new javax.swing.JLabel();
        lblSzoveg = new javax.swing.JLabel();
        lblSzoveg4 = new javax.swing.JLabel();
        lblSzoveg3 = new javax.swing.JLabel();
        btnEletero = new javax.swing.JButton();
        lblHatter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSzoveg2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg2.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg2.setText("Sűrű barna spórafelhő csap ki a golyóból, és körülvesz");
        getContentPane().add(lblSzoveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        lblSzoveg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg.setText("Kardod könnyedén áthatol a spóragolyó vékonykülső burkán.");
        getContentPane().add(lblSzoveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblSzoveg4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg4.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg4.setText("Veszítesz 2 életpontot!");
        getContentPane().add(lblSzoveg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        lblSzoveg3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg3.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg3.setText("Néhány spóra rádragad, daganatokat okoz.");
        getContentPane().add(lblSzoveg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnEletero.setBackground(new java.awt.Color(255, 51, 51));
        btnEletero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEletero.setForeground(new java.awt.Color(255, 255, 255));
        btnEletero.setText("-2 ÉLETERŐ");
        btnEletero.setMinimumSize(new java.awt.Dimension(80, 30));
        btnEletero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleteroActionPerformed(evt);
            }
        });
        getContentPane().add(btnEletero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 300, 100));

        lblHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hattereszak.png"))); // NOI18N
        lblHatter.setText("jLabel1");
        getContentPane().add(lblHatter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEleteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleteroActionPerformed
        dispose();
    }//GEN-LAST:event_btnEleteroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kettevag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kettevag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kettevag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kettevag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kettevag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEletero;
    private javax.swing.JLabel lblHatter;
    private javax.swing.JLabel lblSzoveg;
    private javax.swing.JLabel lblSzoveg2;
    private javax.swing.JLabel lblSzoveg3;
    private javax.swing.JLabel lblSzoveg4;
    // End of variables declaration//GEN-END:variables
}
