/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

import javax.swing.JOptionPane;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class KinyitodDoboz extends javax.swing.JFrame {

    /**
     * Creates new form EszakFrame
     */
    public KinyitodDoboz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSzoveg = new javax.swing.JLabel();
        lblSzoveg2 = new javax.swing.JLabel();
        lblSzoveg3 = new javax.swing.JLabel();
        lblSzoveg4 = new javax.swing.JLabel();
        btnUzenet = new javax.swing.JButton();
        btnGyerunk = new javax.swing.JButton();
        lblHatter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSzoveg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg.setText("A doboz teteje könnyedén nyílik. Benne két aranypénzt találsz");
        getContentPane().add(lblSzoveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lblSzoveg2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg2.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg2.setText("És egy üzenetet, ami neked szól:");
        getContentPane().add(lblSzoveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        lblSzoveg3.setBackground(new java.awt.Color(255, 255, 51));
        lblSzoveg3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg3.setForeground(new java.awt.Color(255, 255, 0));
        lblSzoveg3.setText("Megjegyzed a tanácsot, apródarabokra téped a pergament,");
        getContentPane().add(lblSzoveg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lblSzoveg4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg4.setForeground(new java.awt.Color(255, 255, 0));
        lblSzoveg4.setText("és tovább mész észak felé.");
        getContentPane().add(lblSzoveg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        btnUzenet.setBackground(new java.awt.Color(255, 51, 51));
        btnUzenet.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        btnUzenet.setForeground(new java.awt.Color(255, 255, 255));
        btnUzenet.setText("ÜZENET");
        btnUzenet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUzenetActionPerformed(evt);
            }
        });
        getContentPane().add(btnUzenet, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 110, 60));

        btnGyerunk.setBackground(new java.awt.Color(255, 51, 51));
        btnGyerunk.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        btnGyerunk.setForeground(new java.awt.Color(255, 255, 255));
        btnGyerunk.setText("GYERÜNK");
        btnGyerunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGyerunkActionPerformed(evt);
            }
        });
        getContentPane().add(btnGyerunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, 60));

        lblHatter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hatter.jpg"))); // NOI18N
        lblHatter.setText("jLabel1");
        getContentPane().add(lblHatter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUzenetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUzenetActionPerformed
       JOptionPane.showMessageDialog(rootPane, "„Jól tetted. Legalább volt annyi eszed, hogy megállj és elfogadd az ajándékot. \nMost azt tanácsolom neked, hogy keress és használj különféle tárgyakat, \nha sikerrel akarsz áthaladni Halállabirintusomon.” \nAláírás: Szukumvit", "REJTELMES ÜZENET", 1);
    }//GEN-LAST:event_btnUzenetActionPerformed

    private void btnGyerunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGyerunkActionPerformed
     new Eszak().setVisible(true);
     dispose();
    }//GEN-LAST:event_btnGyerunkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KinyitodDoboz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KinyitodDoboz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KinyitodDoboz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KinyitodDoboz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KinyitodDoboz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGyerunk;
    private javax.swing.JButton btnUzenet;
    private javax.swing.JLabel lblHatter;
    private javax.swing.JLabel lblSzoveg;
    private javax.swing.JLabel lblSzoveg2;
    private javax.swing.JLabel lblSzoveg3;
    private javax.swing.JLabel lblSzoveg4;
    // End of variables declaration//GEN-END:variables
}
