/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class Nyugat extends javax.swing.JFrame {

    /**
     * Creates new form Nyugat
     */
    public Nyugat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSzoveg = new javax.swing.JLabel();
        lblSzoveg2 = new javax.swing.JLabel();
        btnEszak = new javax.swing.JButton();
        btnNyuga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSzoveg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg.setText("A három pár nedves lábnyomot követve az alagútnyugati");
        getContentPane().add(lblSzoveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        lblSzoveg2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSzoveg2.setForeground(new java.awt.Color(255, 255, 255));
        lblSzoveg2.setText("elágazásában hamarosan egy újabb el-ágazáshoz érsz.");
        getContentPane().add(lblSzoveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        btnEszak.setBackground(new java.awt.Color(255, 51, 51));
        btnEszak.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        btnEszak.setForeground(new java.awt.Color(255, 255, 255));
        btnEszak.setText("ÉSZAK");
        btnEszak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEszakActionPerformed(evt);
            }
        });
        getContentPane().add(btnEszak, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 140, 90));

        btnNyuga.setBackground(new java.awt.Color(255, 51, 51));
        btnNyuga.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        btnNyuga.setForeground(new java.awt.Color(255, 255, 255));
        btnNyuga.setText("NYUGAT");
        btnNyuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyugaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNyuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hattereszak.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEszakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEszakActionPerformed
        new Eszak2().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEszakActionPerformed

    private void btnNyugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyugaActionPerformed
        new Nyugat2().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNyugaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nyugat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nyugat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nyugat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nyugat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nyugat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEszak;
    private javax.swing.JButton btnNyuga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSzoveg;
    private javax.swing.JLabel lblSzoveg2;
    // End of variables declaration//GEN-END:variables
}
